### ISSUE TITLE
Work on responsiveness of parallax image.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#10]
Desktop view : 
![desktop](https://user-images.githubusercontent.com/26071627/31072792-f0f4cc28-a758-11e7-9c67-787f7236a842.png)
Mobile  view : 
![screenshot from 2017-10-02 15-37-02](https://user-images.githubusercontent.com/26071627/31072969-8fce260a-a759-11e7-82ab-5e8909c4abb2.png)

Fix needed.

**Comment by sautumn** [comment]
Care if I work on this issue?

**Comment by chaitanyagiri** [comment]
@sautumn  Sure go on.
