### ISSUE TITLE
On hovering over links in footer, the alignment gets disturbed

### ISSUE THREAD

**Issue by vishalsanghai** [Cybros/Cybros-Web-Application#100]
In shortcut section of footer, when we hover over a link, the whole footer shakes. 
(This is because, when we hover over a link, it's font-size increases, taking more space, and disturbing the alignment.)

Possible Approach : Put each link in a div with giving some extra space, to compensate for larger font-size on hovering.

**Comment by chaitanyagiri** [comment]
Thanks for contributing to the repository.

**Comment by teevik** [comment]
Hey, pretty sure i know how to fix it, 1 sec can see

**Comment by chaitanyagiri** [comment]
@teevik  thanks for showing interest, although this issue was resolved you may go to the issues section and resolve them also if you like this repository please give us a star and show your support. :+1:

**Comment by teevik** [comment]
Ah ok 😃 np
