### ISSUE TITLE
Make signup form responsive.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#11]
Sign up/Sign in form is not responsive.
![screenshot from 2017-10-02 15-40-22](https://user-images.githubusercontent.com/26071627/31073143-409727ac-a75a-11e7-9e3e-d5ff5e985af7.png)

**Comment by jimjja** [comment]
I can work on this

**Comment by chaitanyagiri** [comment]
Go on.

**Comment by suleimanbashiru** [comment]
Is this still available.

**Comment by chaitanyagiri** [comment]
@suleimanbashiru We already got a merge request you can look up to some other issues or even create one.
