### ISSUE TITLE
Write content for about us page

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#16]
Anyone versed in writing skills can help us in writing content for "about us" page. 
Discuss what you need to write in [gitter](https://gitter.im/LNMIIT-Computer-Club/Lobby) channel.

**Comment by digilou** [comment]
I can help in this area.

**Comment by chaitanyagiri** [comment]
@digilou  Go on waiting for your PR.

**Comment by digilou** [comment]
Hi @chaitanyagiri I'm having trouble pushing my branch.
`remote: Permission to Cybros/Cybros-Web-Application.git denied to digilou.
fatal: unable to access 'https://github.com/Cybros/Cybros-Web-Application.git/': The requested URL returned error: 403` Any suggestions?

**Comment by divyanshu-rawat** [comment]
hi, @digilou you need to fork the repo. first, then you have to make changes in your forked copy and when you are done with making changes in the forked copy send pull request we will be more than happy to merge it.
Looking forward to your PR.
If you have any doubts please let us know.
