### ISSUE TITLE
Adjust fonts in the form(signup.hbs) and side navigation so that its visible clearly.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#20]
In some browsers(Chrome) fonts become too thin and are not clearly visible try correcting it.

**Comment by firdausmaarof** [comment]
@chaitanyagiri Hi, is this #21 acceptable?

**Comment by chaitanyagiri** [comment]
@firdausmaarof  Please attach screenshots from both firefox and chrome.

**Comment by firdausmaarof** [comment]
Chrome:
<img width="1440" alt="screen shot 2017-10-03 at 5 23 44 pm" src="https://user-images.githubusercontent.com/10150564/31118389-d32ec4f2-a85f-11e7-8dd9-3f93ca46cbd4.png">

Firefox:
<img width="1440" alt="screen shot 2017-10-03 at 5 25 53 pm" src="https://user-images.githubusercontent.com/10150564/31118451-02820534-a860-11e7-9dda-7f742156eb07.png">

**Comment by chaitanyagiri** [comment]
@firdausmaarof  Thanks for contributing. I'll merge your PR now meanwhile you may take a look to the web application and suggest some UI improvements, or work on previous issues. Happy coding.
