### ISSUE TITLE
There should be an issue and PR template

### ISSUE THREAD

**Issue by ParthS007** [Cybros/Cybros-Web-Application#24]
I would like to add an issue and PR template as it will provide more clarity on the issue and PRs

**Comment by ParthS007** [comment]
Your views @chaitanyagiri

**Comment by chaitanyagiri** [comment]
@ParthS007  go on create one. It must consist Referenced issue, Star mark repository :p and what else? suggest something?

**Comment by ParthS007** [comment]
It is similar to what I have committed to paper.lnmiit repo.have a look at it and suggest changes if required. :grinning:

**Comment by chaitanyagiri** [comment]
Okay then add checklist:
1. My branch is up to date
2. I have starred repository
3. Referenced issue(if any)
4. Changes made

waiting for your PR
