### ISSUE TITLE
Make a better looking admin page.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#26]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
adminlogin.hbs page sucks lookwise.

**Expected behaviour:**

A tidy looking admin login page that matches current theme.

**Steps to reproduce:**

**Comment by chaitanyagiri** [comment]
@ParthS007 there you go.

**Comment by ParthS007** [comment]
working on it @chaitanyagiri :slightly_smiling_face:

**Comment by BestDanelleEver** [comment]
Can i take this?

**Comment by chaitanyagiri** [comment]
@BestDanelleEver  this is already assigned and he might have done it already. If you want you may work on other issues or open a new one. :)
