### ISSUE TITLE
Make about us page look better.

### ISSUE THREAD

**Issue by kaushal8298** [Cybros/Cybros-Web-Application#30]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

About page should not contain about section in footer

**Comment by chaitanyagiri** [comment]
@kaushal8298  thanks for contributing. I was thinking if you can format whole about us page(changing font, font-size adding names and links to coordinator's account). Please let me know if you are willing to do it? Also try attaching a screenshot of the changes in design. Happy coding.
