### ISSUE TITLE
Add navigation to footer's shortcut menu.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#34]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Footer's shortcut menu do not navigate users.

**Expected behaviour:**
Users will be able to navigate from Shortcut menu in footer.

put a 'x' inside [ ] to check.
**Steps to reproduce:**

**Comment by Jeffrey-Chang** [comment]
@chaitanyagiri I finished this request. You can view it here https://github.com/Cybros/Cybros-Web-Application/issues/34

**Comment by chaitanyagiri** [comment]
Thanks for contributing, please have a look at some other issues in the repository and try solving them if possible create a new issue and then solve it. :)

**Comment by divyanshu-rawat** [comment]
thanks for the PR. 👍
