### ISSUE TITLE
Make admin panel's button responsive and better looking.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#35]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behaviour:**
In adminpanel.hbs buttons need to be fixed for mobile devices.
**Expected behaviour:**
Nice responsive and good looking buttons in adminpanel.hbs

put a 'x' inside [ ] to check.
**Steps to reproduce:**

**Comment by rowhitswami** [comment]
I'd love to work on this :blush:

**Comment by divyanshu-rawat** [comment]
ya cool 👍

**Comment by rowhitswami** [comment]
#57 Please review PR.
