### ISSUE TITLE
Can not login with manually inserted admin user

### ISSUE THREAD

**Issue by davidbru** [Cybros/Cybros-Web-Application#43]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Can not login with manually inserted admin user.

**Expected behaviour:**
Proper login

**Steps to reproduce:**
README.md says: 
`db.admin.insert({username:"testadmin", Password:"testpassword", Hasaccess:true});`

But models/Admin.js defines HasAccess and not Hasaccess.

Even if I insert 
`db.admin.insert({username:"testadmin", Password:"testpassword", HasAccess:true});`
I can not login on http://localhost:3000/admin/

As far as I can trace it back, the following line in routes/admin.js can not find a user for the posted username:
Admin.find({username:req.body.username},function(err,admin){})

**Comment by chaitanyagiri** [comment]
@davidbru  Thanks for contributing, I am so glad that you took time to analyse the application. However, there was a slight mistake from our side since MongoDB has a tendency to convert collection name to their plural forms. try using
`db.admins.insert({username:"testadmin", Password:"testpassword", HasAccess:true});`
By the way thankyou soo much you indirectly helped me to resolve another bug. :smile:

**Comment by davidbru** [comment]
Still not working for me.
I tried it, but the line
`Admin.find({username:req.body.username},function(err,admin){})`
still doesn't let me log in.

Any idea what still is wrong?

**Comment by chaitanyagiri** [comment]
Have you tried doing a find operation in Mongo terminal?

**Comment by davidbru** [comment]
`> db.admin.find()`
--> no result

```
> db.admins.find()
{ "_id" : ObjectId("59de64360095cf5493029091"), "username" : "testadmin", "Password" : "testpassword", "HasAccess" : true }

```

**Comment by chaitanyagiri** [comment]
@davidbru  I tried in some other devices also and its working in them. Try updating NodeJS and MongoDB to their latest stable version.

**Comment by davidbru** [comment]
```
mongod -v
db version v3.4.9
```

```
node -v
v8.4.0
```

```
npm -v
5.4.2
```

**Comment by davidbru** [comment]
I was wondering: maybe my local app does not have access to the database at all.
Is there a way to check if the database connection is working at all?

I can navigate the normal pages, but I suspect, that for those part's I don't need a db connection.

**Comment by chaitanyagiri** [comment]
Try signing up as a user also first pull the changes first.

**Comment by davidbru** [comment]
Pulled the current changes, but now the website does not work at all and there is still debug info in the header.hbs..

```
<<<<<<< HEAD

                <img class="img-responsive" style="display: block;
                        margin-left: auto;
                        margin-right: auto;" src="/favicon.png" alt="logo" width="100" height="60">
                
=======
                <img class="img-responsive" style="display: block;
                        margin-left: auto;
                        margin-right: auto;" src="/favicon.png" alt="logo" width="100" height="60">
>>>>>>> 6c59772f630aca48835a917aed4cf15447431bee
```

**Comment by chaitanyagiri** [comment]
Sorry for the inconvenience, actually that code was accidentally put by my IDE now its fine check it now. :+1:

**Comment by davidbru** [comment]
Pulled the newest version. The above mentioned error is now gone, but the application is still not working.
It keeps on loading, and the console shows:
```
Magic happens in port: 3000
No events featured
```

**Comment by chaitanyagiri** [comment]
Check it now I've fixed it and tell me about your database issue?

**Comment by davidbru** [comment]
So the application now works with the current version of the code.

I can create a new user via the webinterface and can also log in. I see the created user in the database. So the database connection is working.

I also see that on initializing the application via `npm start` there is a collection called "admins" created in the database.
However if I insert a new admin user manually into the collection it won't let me log in in the application.

**Comment by chaitanyagiri** [comment]
BTW thanks you helped me in finding a lot of bugs.

**Comment by davidbru** [comment]
you are welcome
