### ISSUE TITLE
Alternatives to Global Variable in express 4 

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#5]
Currently, I implemented the functionality: "That a GLOBAL variable is used to carry a user's details for a current session as I have to use it in different files(middlewares)". I don't want to use a GLOBAL variable so, I am looking for alternatives to it in express 4.

**Comment by divyanshu-rawat** [comment]
just export an object containing user details and import that where you want to use it I guess it will work !

**Comment by chaitanyagiri** [comment]
Thanks . This issue can be solved with that but I just now figured out that we need to reset user data for every client so I need to figure out some other way around (maybe socket.io'd work).
