### ISSUE TITLE
When clicked in date part of event the event detail's alignment gets disturbed

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#50]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
When clicked in date part of the event, the event detail's alignment gets disturbed.
the problem persists in (profile details also).

![](https://user-images.githubusercontent.com/32520655/31550025-7dfa0632-b01f-11e7-9c72-97bf7b0939e5.png)

**Expected behaviour:**
event detail's alignment must not alter when clicked on certain elements.

put a 'x' inside [ ] to check.
**Steps to reproduce:**

**Comment by LuisHansen** [comment]
Working on it!

**Comment by chaitanyagiri** [comment]
@LuisHansen waiting for your PR. :+1:
