### ISSUE TITLE
Loading with no events

### ISSUE THREAD

**Issue by LuisHansen** [Cybros/Cybros-Web-Application#55]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

The main page doesn't work if no events are saved in the database.

**Expected behaviour:**

Everything should work even if no events are set.

**Steps to reproduce:**

Just remove every event from mongo and try to access the main page.

**Comment by LuisHansen** [comment]
I'm already working on this.
Actually, the issue is just for documentation.

**Comment by chaitanyagiri** [comment]
Good work with conditional operators but we usually avoid conditional operators in development period as it decreases the readability of the application. Also, I fixed the issue just before you created it so thanks for PR, try stashing and pulling changes.
