### ISSUE TITLE
Unexpected data in form of key-value pair in menu

### ISSUE THREAD

**Issue by rowhitswami** [Cybros/Cybros-Web-Application#59]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
A string came in the menu upon clicking the menu drawer.
```javascript

                    { _id: 59dfe35df3xxxxxxxxxxxxx,
  Hasaccess: true,
  HasAccess: false,
  Password: 'xxxxxx',
  username: 'rowhit' }
   ```

**Expected behaviour:**
It should show the name of admin who is currently logged in.

**Steps to reproduce:**
- [x] Changing the respective file with correct path

**Comment by chaitanyagiri** [comment]
Hey, I tried everything is working fine try pulling new changes your fork is 30 commits behind.

**Comment by rowhitswami** [comment]
yes @chaitanyagiri, I forgot to pull. Thanks for your quick response. Can you please review my PR #57
