### ISSUE TITLE
Neither Workshop nor Classes link works now..

### ISSUE THREAD

**Issue by guptajeetesh7** [Cybros/Cybros-Web-Application#63]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
No view is rendered as if now.

**Expected behaviour:**
View should be generated.

put a 'x' inside [ ] to check.
**Steps to reproduce:**

**Comment by chaitanyagiri** [comment]
Hey, @guptajeetesh7 thanks for helping us find a new bug in the app. I've resolved it pull the latest changes.
