### ISSUE TITLE
New_user must direct to login page

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#65]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
when clicked on "New_user" user is shown login and profile.

**Expected behaviour:**
when clicked on "New_user" user must be directed to login page 

put a 'x' inside [ ] to check.
**Steps to reproduce:**

**Comment by guptajeetesh7** [comment]
@chaitanyagiri  I m ready to submit PR. Thanks
