### ISSUE TITLE
Cleanup the .gitignore file

### ISSUE THREAD

**Issue by karanagarwal17** [Cybros/Cybros-Web-Application#76]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] chore

**Current behaviour:**
The current gitignore has a lot of unused code.

**Expected behaviour:**
Ideally it should contain only the file/directory names which are present and have to be ignored.

**Comment by chaitanyagiri** [comment]
@cheepo2109 thanks for contributing, actually you need to send a Pull Request to the Cybros-Web-Application:master and before sending a pull request please pull the changes from the repository.
