### ISSUE TITLE
remove the node_modules from the repo

### ISSUE THREAD

**Issue by karanagarwal17** [Cybros/Cybros-Web-Application#77]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] chore

**Current behaviour:**
The repo contains the node modules making it heavy to clone

**Expected behaviour:**
The node_modules should be removed and the dependencies in the package.json should be updated if needed.

**Comment by rakshans1** [comment]
let me work on this

**Comment by chaitanyagiri** [comment]
@rakshans1  thanks for contributing please have a look at some of the other issues or create any new issue and mark a star to the repository if you liked it.
