### ISSUE TITLE
The navbar button is on the opposite side from the side nav menu

### ISSUE THREAD

**Issue by karanagarwal17** [Cybros/Cybros-Web-Application#78]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] UX Improvement

**Current behaviour:**
The sidenav toggle button is on the right side and the sidenav is on the left. So, a user has to travel across the screen to use the sidenav after clicking the toggle button.

**Expected behaviour:**
Both the sidenav and toggle button should be on the same side.

**Comment by SoerenTerh** [comment]
Toggled navigation menu is now moved to the right side while maintaining the functionality of the button by setting the z-index accordingly. Should be sufficient like this, since I would keep the logo on the left side.

**Comment by karanagarwal17** [comment]
Thanks for your PR. 
I think this should be sufficient. 
Waiting for the other reviewers.
