### ISSUE TITLE
User details must be emailed to the user email ID.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#79]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

After signing up user may forget his/her user details so we must send necessary details to his/her email ID.
**Steps to reproduce:**
nodemailer can be used here

**Comment by abdulsamad234** [comment]
Hey, i would like to work on this issue for you, any pointers?

**Comment by karanagarwal17** [comment]
@abdulsamad234, You can find a good tutorial [here](http://adilapapaya.com/docs/nodemailer/)

**Comment by kaysiz** [comment]
@karanagarwal17 i would like to take a crack at it.
