### ISSUE TITLE
Using one Server Instance

### ISSUE THREAD

**Issue by rakshans1** [Cybros/Cybros-Web-Application#83]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
Currently every route is using its own instance of express in routes/*.js

**Expected behaviour:**
We should create only on instance of express in app.js and pass it to the routers to be used by them.

```
var express = require('express');
var  bodyParser =  require('body-parser');

var router = require('./routes/index');

var app = express();
const jsonParser = bodyParser.json({type: '*/*'});

router(app, jsonParser);
```
In router file  routes/index
```
export default function(app, jsonParser) {
     app.get('/', requireAuth, (req, res) => {
        res.send('hi ' + req.user.name);
    });

    ...
}
```

This will use same instance of express and middlewares will be added only in app.js

**Comment by karanagarwal17** [comment]
Every route does need to require the express router for its use, but it does not need to initiate a new app for every route. 

The routes of the project need a lot of re-factoring, I will open separate issues by breaking the re-factor into small tasks.
