### ISSUE TITLE
Improve the sidenav

### ISSUE THREAD

**Issue by karanagarwal17** [Cybros/Cybros-Web-Application#90]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Currently the sidenav only closes when the toggle button is clicked. And it is translucent.

**Expected behaviour:**
When sidenav is open, clicking anywhere on the page except for the sidenav should close it. And it should be made opaque.

**Comment by abhanshgiri21** [comment]
i would like to work on this. Can i get some more details as to which files are concerned with this feature??

**Comment by karanagarwal17** [comment]
@abhanshgiri21, the JS for the feature is present in public/js/index.js and the html is in views/partials/adminheader.hbs

**Comment by abhanshgiri21** [comment]
i am on it.
i will make the background of sidenav white and opaque.
would try to add the functionality that sidenav closes when we click anywhere else on page.
i am doing this right now so please be active as if i need any more help i will comment right away. i would love a fast reply.
thanks

**Comment by abhanshgiri21** [comment]
i did it. the sidenav is now opaque with white background and it disappears if its open when clicked anywhere else on page. please close this issue.

**Comment by karanagarwal17** [comment]
Submit your commit referencing this issue.

**Comment by abhanshgiri21** [comment]
i downloaded the zip and made the changes on my local machine. unfortunately this is my first time contributing to a open source project. Can you tell me how to make the pull request. I have edited files on my local machine. What do i do now?

**Comment by abhanshgiri21** [comment]
nevermind , i figured it out and made a commit.

**Comment by chaitanyagiri** [comment]
@abhanshgiri21  nice work. Please have a  look at some other issues or create a new issue if you find one.
