### ISSUE TITLE
Add a view for admin to see the registrations data through admins dashboard.

### ISSUE THREAD

**Issue by chaitanyagiri** [Cybros/Cybros-Web-Application#95]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Admin can not see registrations data via website.

**Expected behaviour:**
Admin will be able to see registrations data via website.

**Comment by danswater** [comment]
hi can i try this?

**Comment by chaitanyagiri** [comment]
Go on @danswater

**Comment by PrajapatiAnkit** [comment]
can i work on this??

**Comment by chaitanyagiri** [comment]
@PrajapatiAnkit  go on we'll consider the first person to send PR.
